export const ITEMS_CHECKLIST_ALISTAMIENTO = [
  'Cambio de aceite / verificación del kilometraje',
  'Velocímetro',
  'Retrovisores',
  'Sistema de embrague',
  'Freno delantero',
  'Freno trasero',
  'Mandos',
  'Amortiguadores delanteros',
  'Amortiguadores traseros',
  'Exosto',
  'Protector de cadena',
  'Sistema de transmisión de fuerza',
  'Sin fuga de aceites ni combustible',
  'Rines en buen estado',
  'Llantas en buen estado (con labrado visible)',
  'Luz frontal',
  'Luz trasera',
  'Luces de freno',
  'Luces direccionales',
  'Pito',
  'Aseo general, interno y externo',
  'Casco en buen estado',
  'Casco identificado (placa de la moto)',
  'Guantes en buen estado',
  'Impermeable en buen estado',
  'Chaleco reflectivo en buen estado',
  'Botas con punta de acero',
  'Cédula de ciudadanía',
  'Licencia de conducción A2 vigente',
  'Revisión técnico-mecánica y certificado de gases vigente original',
  'Tarjeta de propiedad vigente original',
  'Seguro obligatorio vigente original (SOAT)',
] as const;
